services:
  mongodb:
    image: mongo:8.0.15-noble
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: book_management_api_user
      MONGO_INITDB_ROOT_PASSWORD: book_management_user_pass
      MONGO_INITDB_DATABASE: book_management_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app

  book-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: book-management-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: development
      PORT: 3000
      DATABASE_URL: mongodb://mongodb:27017
    depends_on:
      - mongodb
    networks:
      - app
volumes:
  mongo_data:

networks:
  app:
    driver: bridge