services:
  mongodb:
    image: mongo:8.0.15-noble
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: book_management_api_user
      MONGO_INITDB_ROOT_PASSWORD: book_management_user_pass
      MONGO_INITDB_DATABASE: book_management_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app

volumes:
  mongo_data:

networks:
  app:
    driver: bridge